<?php

/**
 * Build the shipped stylesheet from a local @milpa/design release. No application build step.
 * Usage: php scripts/build-component-styles.php /path/to/@milpa/design [--check]
 * Apache-2.0 · (c) Rodrigo Vicente - TeamX Agency
 */

declare(strict_types=1);

$source = rtrim($argv[1] ?? '', '/');
$package = json_decode((string) file_get_contents($source . '/package.json'), true, 512, JSON_THROW_ON_ERROR);
if (($package['name'] ?? '') !== '@milpa/design') {
    throw new RuntimeException('Expected the @milpa/design package');
}
$files = ['motion/milpa-motion.css', 'primitives/milpa-primitives.css', 'components/milpa-components.css', 'artifacts/milpa-artifacts.css', 'layouts/milpa-layouts.css'];
$css = "/* @milpa/design@{$package['version']} — generated by scripts/build-component-styles.php.\n"
    . " * Apache-2.0 · (c) Rodrigo Vicente - TeamX Agency. Load DesignTokens fonts locally. */\n";
$hashes = [];
foreach ($files as $file) {
    $contents = file_get_contents($source . '/' . $file);
    if ($contents === false || preg_match('/@import|url\s*\(/i', $contents)) {
        throw new RuntimeException('Missing stylesheet or undeclared resource dependency: ' . $file);
    }
    $hashes[$file] = hash('sha256', $contents);
    // The generated artifact carries one English provenance header; source comments remain upstream.
    $withoutComments = (string) preg_replace('~/\*.*?\*/~s', '', $contents);
    $css .= "\n/* " . $file . " */\n" . trim((string) preg_replace('/[\t ]+$/m', '', $withoutComments)) . "\n";
}
$outputs = [
    'milpa-components.css' => $css,
    'milpa-components.source.json' => json_encode(['package' => '@milpa/design', 'version' => $package['version'], 'license' => 'Apache-2.0', 'source' => 'https://github.com/getmilpa/milpa-design', 'sha256' => $hashes], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n",
];
foreach ($outputs as $name => $contents) {
    $path = dirname(__DIR__) . '/resources/design/' . $name;
    if (in_array('--check', $argv, true)) {
        if (!is_file($path) || file_get_contents($path) !== $contents) {
            throw new RuntimeException('Generated artifact differs: ' . $name);
        }
    } else {
        file_put_contents($path, $contents);
    }
}
